### ISSUE TITLE
you cant delete github messages lol

### ISSUE THREAD

**Issue by Dxgamer7405** [0xDrMoe/TownofHost-Enhanced#1060]
you cant delete github messages lol

_Originally posted by @Pietrodjaowjao in https://github.com/0xDrMoe/TownofHost-Enhanced/issues/1055#issuecomment-2211557346_

**Comment by NikoCat233** [comment]
moe can manually delete it

**Comment by Ultradragon005** [comment]
WHAT THE KURWA BLYAT IS GOING ON HERE

**Comment by Ultradragon005** [comment]
#1061 
#1055 
#1059 
#999 
#1012 
#1057 
#1052 
#815 
#831 
#934 
#954 
#1036

**Comment by Dxgamer7405** [comment]
uhmm, what the sigma?

**Comment by GameTechGuides** [comment]
exciting!
