### ISSUE TITLE
Not the best mod for "Anyone wanting to change their Among Us Experience" anymore. This is False Advertising.

### ISSUE THREAD

**Issue by LoonieRoons** [0xDrMoe/TownofHost-Enhanced#1099]
Original Poster: Discord Tag (itz.loonie)
Version: GitHub
Original Date of Issue: (Date) ?

Fix Attempted Before? No
Map: All
Reproducible? Yes/No/Have not attempted
Description/Additional Notes: Change it. TOHE-Reborn is the better mod.

**Comment by Tommy-XL** [comment]
Bro

**Comment by NotPyro404** [comment]
reborn is better yet is forked from the :skull: you really don't have a brain do you idiot

**Comment by NotPyro404** [comment]
was at a loss for words at the skull, meant to say "forked from the 'repository'"

**Comment by Ultradragon005** [comment]
this is fake advertizing. I am gonna sue you for commiting a ferlony young man, you better be prepared for jury duty

**Comment by Ultradragon005** [comment]
1943.213.1243.0.10.0.0.1

**Comment by NotPyro404** [comment]
> > reborn is better yet is forked from the 💀 you really don't have a brain do you idiot
> 
> "The 💀", You don't have a brain.

You don't have programming skills 😂 

wonder if youll fuck this one up too, you Re-ally need to get better branding since Re-edited flipped, Re-fined never existed, and Re-born is gonna follow

**Comment by NotPyro404** [comment]
> > 1943.213.1243.0.10.0.0.1
> 
> Reported.

there you go again with the re-stuff

**Comment by Ultradragon005** [comment]
![image](https://c.tenor.com/spJePCsFHlEAAAAd/tenor.gif)

**Comment by NotPyro404** [comment]
that's crazy false info I'm not even a contributor idiot

**Comment by NotPyro404** [comment]
hey loonie can you buy Moe a phone so he'll release a stable build

**Comment by NotPyro404** [comment]
dude where you go I have a role idea for you to steal and make into a buggy mess

**Comment by MargaretTheFool** [comment]
![mods-help-rule-v0-mvddkhv27orc1_png](https://github.com/user-attachments/assets/cd554e1c-ca6e-4f8e-82ba-1692fcfb2213)

**Comment by HyperAtill** [comment]
You won't prove anything to each other. Argument for the sake of argument

**Comment by impostor4291** [comment]
I created a Github account just to say to you that :
Can you stop?What does it bring to you to bother us like this?

**Comment by Pietrodjaowjao** [comment]
> > 1943.213.1243.0.10.0.0.1
> 
> Reported.

DEPORTED.

**Comment by 0xDrMoe** [comment]
god, this thing is so annoying, you're not him, you're not coo, fuck off, and stay off. Didn't you quit among us? go back to town of shit 2
