### ISSUE TITLE
Discord Moderator and Contributor harassing me

### ISSUE THREAD

**Issue by LoonieRoons** [0xDrMoe/TownofHost-Enhanced#1100]
> > 1943.213.1243.0.10.0.0.1
> 
> Reported.

there you go again with the re-stuff

_Originally posted by @NotPyro404 in https://github.com/0xDrMoe/TownofHost-Enhanced/issues/1099#issuecomment-2236925792_

**Comment by Ultradragon005** [comment]
![image](https://github.com/user-attachments/assets/37f02e08-d494-4874-9e40-fde40d8ead20)

**Comment by NotPyro404** [comment]
I live in your head rent free. I have my feet up, sipping a cold.. lemonade, none of that alcoholic stuff, bad for your brain. maybe helpful for yours but, that's besides the point. I dog walk you. The fact I code and have 0 clue what I'm doing and still have less bugs in my code than you is crazy. How long you been coding for? You could argue harassment, I argue however that you've been harassing TOHE and others for months now so, we're even. Probably not actually even, bitch a decimal.

**Comment by Dxgamer7405** [comment]
hey loonie im big fan i can have a shoutout

**Comment by HyperAtill** [comment]
> > I live in your head rent free. I have my feet up, sipping a cold.. lemonade, none of that alcoholic stuff, bad for your brain. maybe helpful for yours but, that's besides the point. I dog walk you. The fact I code and have 0 clue what I'm doing and still have less bugs in my code than you is crazy. How long you been coding for? You could argue harassment, I argue however that you've been harassing TOHE and others for months now so, we're even. Probably not actually even, bitch a decimal.
> 
> You're the one who just wrote a paragraph?

What do you think you'll prove to someone?...
None of you will agree with each other

**Comment by NotPyro404** [comment]
You keep coming back you like the fnaf dude but annoying as shit and gets 0 women (or men, we love all people here), and even if you did the only ones you got are on a sleep call

**Comment by NotPyro404** [comment]
> > > I live in your head rent free. I have my feet up, sipping a cold.. lemonade, none of that alcoholic stuff, bad for your brain. maybe helpful for yours but, that's besides the point. I dog walk you. The fact I code and have 0 clue what I'm doing and still have less bugs in my code than you is crazy. How long you been coding for? You could argue harassment, I argue however that you've been harassing TOHE and others for months now so, we're even. Probably not actually even, bitch a decimal.
> > 
> > 
> > You're the one who just wrote a paragraph?
> 
> What do you think you'll prove to someone?... None of you will agree with each other

cuz there's no agreement
one of us is a stupid and dumb boy
the others a manipulative idiot who keeps tryna squeeze their way back in

**Comment by HyperAtill** [comment]
Ok it seems to me I'm not able to stop that...
Have a nice day @everyone
Bye

**Comment by Ultradragon005** [comment]
![image](https://github.com/user-attachments/assets/3d20bbe3-e8fc-4e38-b0aa-f93aa59fae9e)

**Comment by NotPyro404** [comment]
Loonie.. c- come back!! I.. I miss you.. pookie.. 🥺
