### ISSUE TITLE
[FR] Add new settings for Sheriff and doctor

### ISSUE THREAD

**Issue by VixenSugo** [0xDrMoe/TownofHost-Enhanced#1101]
- Sheriff: He should not be able to use sabotage and doors

- Doctor: The doctor can anonymously chat with the players in the meeting and announce the cause of death. quick chat and free chat.

You can change two of the game's default chats with bite or kill options for the role of the doctor. so that when the doctor selects certain text shortcuts in quick chat, the bite or kill message will be sent in the form of a system message or host message in the chat section.
In this case, in games where evil gusser is present or not, they cannot guess or kill the doctor quickly. For free chat, you can use commands similar to guessers

**Comment by Tommy-XL** [comment]
The first one cannot be done because the AU code does not provide data about the player who is trying to close the doors. But others sabotages are being tracked (Innersloth logic is amazing)

**Comment by Tommy-XL** [comment]
For similar suggestions there is a Discord server TOHE, lol

**Comment by Pietrodjaowjao** [comment]
Ye, dont use issues unless there is a really significant issue
