### ISSUE TITLE
Can't join discord

### ISSUE THREAD

**Issue by SiltrinCaluss** [0xDrMoe/TownofHost-Enhanced#1111]
Whenever I try and join the TOHE discord server to get the Canary build I get kicked instantly for some reason.

**Comment by Pietrodjaowjao** [comment]
Its some issue

**Comment by SiltrinCaluss** [comment]
Frfr

**Comment by Ultradragon005** [comment]
https://www.youtube.com/watch?v=IKDrqkFBNmo
