### ISSUE TITLE
Can't Connect to TOHE API error

### ISSUE THREAD

**Issue by ProSLYT** [0xDrMoe/TownofHost-Enhanced#1126]
i just installed TOHE and when i launch the game it says cant connect to tohe api, idk how to fix this and i cant join the discord cuz it just kicks me instantly

**Comment by ProSLYT** [comment]
how to reproduce: idk man

**Comment by ProSLYT** [comment]
version of TOHE: 2.0

**Comment by KingPanda360** [comment]
The TOHE API is a temporary issue only Moe can fix; no one else can. You will have to wait until there is an announcement that it's fixed, or wait some time and then play among us. The next time you get on, it might be fixed.
