### ISSUE TITLE
Someone delete the last / in the api url

### ISSUE THREAD

**Issue by NikoCat233** [0xDrMoe/TownofHost-Enhanced#1127]
https://github.com/0xDrMoe/TownofHost-Enhanced/blob/5058d218e7f496c72a626aa9283cd168e04a68c4/Modules/dbConnect.cs#L206

**Comment by Pietrodjaowjao** [comment]
why would i do this

**Comment by NikoCat233** [comment]
https://api.bruh.ca//userinfo

**Comment by NotPyro404** [comment]
it'd be so funny if that's what the issue was

**Comment by NikoCat233** [comment]
it is not the issue, but it will be after 2024.8.21 if u do nothing to it

**Comment by NotPyro404** [comment]
someone should do something Abt that huh

**Comment by Pietrodjaowjao** [comment]
i did now

**Comment by NotPyro404** [comment]
I'm like a proud father Pietro great job

**Comment by Pietrodjaowjao** [comment]
ok merge this pr NOW:
https://github.com/0xDrMoe/TownofHost-Enhanced/pull/1128

**Comment by NotPyro404** [comment]
@0xDrMoe @moe.dev whatever it was you should do it yes?
