### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Night-GUA** [0xDrMoe/TownofHost-Enhanced#1137]
I was once banned from TOHRE so I can't play TOHE. I realize my mistake. Is there any way I can unblock it

**Comment by Tommy-XL** [comment]
@0xDrMoe

**Comment by Ultradragon005** [comment]
![image](https://github.com/user-attachments/assets/980806a8-fabd-4477-987a-bccafce9c575)

**Comment by 0xDrMoe** [comment]
so you admitted to hacking and realize that you did but you wanna be unbanned...

**Comment by Night-GUA** [comment]
I know, thank you
