### ISSUE TITLE
Among us mod gains lobby host privileges, kills people in lobby, etc.

### ISSUE THREAD

**Issue by KurtisPeterPerry23** [0xDrMoe/TownofHost-Enhanced#1180]
Hello,

I just wanted to inform how this affecting Among us servers. 

Users are using this in order to gain lobby host privileges and making the servers unplayable. It also completely keeps the user anonymous.

Here is a screenshot of an message that is created:

![evidence](https://github.com/user-attachments/assets/38ecedb3-2c0a-4de5-969e-5d0677c796f2)

I'm not too sure if this is intended or if its just a mod, but people are using it for malicious purposes such as ruining lobbies, games and the overall experience. 

The user can kill people in the lobbies, start the game and then kill everyone in the server. I just wanted to inform you due to these sort of things have a knock on affect.

If you have any questions I am very happy to answer any.

Thank you,

Kurt.

**Comment by Ultradragon005** [comment]
they're not using the mod, they're using a completely different hacked client and impersonating TOHE, for the reason we can only assume being some sort of dissent towards TOHE.

There's nothing we can do about it, and only Innmersloth is able to fix that.

**Comment by KurtisPeterPerry23** [comment]
Hello thank you for getting back so quick. Thank you for the clarification, I thought as much but just wanted to get a concise answer. 

That's all from me then with this. 

Thank you,

Kurt.
