### ISSUE TITLE
Host message in chat issue

### ISSUE THREAD

**Issue by L-Dlbcq** [0xDrMoe/TownofHost-Enhanced#132]
Hi,

In Among Us v2023.10.24s (build 3653), with TOHE v1.1.1, Host can't send message into chat while others players can. And if player with TOHE v1.1.1 join the game, he will had the same issue.

Is there a fix ? Or it's due to new update ?

**Comment by ryuk201198** [comment]
@L-Dlbcq the mod doesn't support the latest update.
Fungle update has broken the mod, we will be updating the mod asap. Until the next release, if you want ro play modded i suggest you downgrade your AU version and host on that.

**Comment by L-Dlbcq** [comment]
@ryuk201198 thanks for your response. I'll wait for the moment until next update ;)
