### ISSUE TITLE
Can't disable Vanilla Mode without restarting the game

### ISSUE THREAD

**Issue by RefriZaddo** [0xDrMoe/TownofHost-Enhanced#186]
this is inconvenient

**Comment by Ultradragon005** [comment]
I don't think that's possible to fix tbh, cuz I'm pretty sure "switch to vanilla" litteraly KILLS tohe.

**Comment by RefriZaddo** [comment]
I don't mind restarting the game tbh
It's just a bit inconvenient but I can get used to it

Em ter., 31 de out. de 2023 14:55, Ultradragon005 ***@***.***>
escreveu:

**Comment by Pyro0TV** [comment]
Yeah this isn't an issue, it just sets your game into Vanilla, which means nothing from the mod. (which means, you cannot switch back unless yk shutting down)
