### ISSUE TITLE
Any plan to rework TOHE with new base of TOH?

### ISSUE THREAD

**Issue by KARPED1EM** [0xDrMoe/TownofHost-Enhanced#239]
seems like devs of TOHE spend too much time on Inconvenient base 😢

**Comment by Ultradragon005** [comment]
wow, but wouldn't that take too much transferring, tohe is super large

**Comment by Tommy-XL** [comment]
Wait, I think you talked to Moe about this

**Comment by Tommy-XL** [comment]
And I think many people know what strong differences there are between the TOH 4.1.2 and 5.1.3 bases

**Comment by KARPED1EM** [comment]
> wow, but wouldn't that take too much transferring, tohe is super large

ikr, what i think is that the later u rework it, the harder it will be

**Comment by 0xDrMoe** [comment]
> > Wait, I thought you talked to Moe about this
> 
> i did, he said its too hard so that he wont do it without me

Yes and no, I would love to, but the team was saying it’s difficult

**Comment by Tommy-XL** [comment]
Maybe, but one day I was studying the TOH 5.0.0 code and realized that it would take a lot of time, and literally ALL the roles and add-ons would need to be rewritten, and not only that, the rest of the TOHE code would also need to be ported

**Comment by Tommy-XL** [comment]
And yet, the algorithm for assigning roles is also very different, this means that the maximum NK and NonNK need to be ported in some way and also the /up command

**Comment by KARPED1EM** [comment]
> 其实我在实际开发中没有遇到什么困难（都得靠tommy和gurge无私的适配doge）

讲真他们比我想象得厉害很多了，而且hyze也说愿意提供帮助。无论TOHE会不会重做，我想他们应该都能做的得很好。但是换新base的话以后应该会轻松很多吧。
