### ISSUE TITLE
Admirer needs a buff 

### ISSUE THREAD

**Issue by StormAoBoy** [0xDrMoe/TownofHost-Enhanced#261]
I don't really like the Admirer role because of it's style, I think like Werewolf's  The Miracle Merchant role is a better version of the Admirer role  The Miracle Merchant is the first to act every night and chooses another player to be the lucky one, who will receive one of three one-time skills: Seer's Check, Witch's Poison or Guard's Protection, limited to each game. once. If the lucky person is a werewolf, he will not gain skills and the Miracle Merchant will be eliminated the next  day
****

**Comment by Ultradragon005** [comment]
h-how, how do you find the place to post it here but not the discord
