### ISSUE TITLE
Taskinator makes everyone doing the target task crash

### ISSUE THREAD

**Issue by Lorddistrict** [0xDrMoe/TownofHost-Enhanced#310]
Version : 1.3.0
Map : Polus
Task : Ship keys & Admin card

What happened : 
The game started, the taskinator did the task then me, then crash :)
Same behaviour for card. This time, multiple players has been kicked.

**Comment by ryuk201198** [comment]
> Version : 1.3.0 Map : Polus Task : Ship keys & Admin card
> 
> What happened : The game started, the taskinator did the task then me, then crash :) Same behaviour for card. This time, multiple players has been kicked.

Taskinator kicking players is a known bug and has been fixed. Please wait for the next release.

**Comment by 0xDrMoe** [comment]
Resolved?

**Comment by Lorddistrict** [comment]
Should we wait the update befaore closing ?

**Comment by Tommy-XL** [comment]
Fixed in dev version, wait for the next release version
