### ISSUE TITLE
Meeting not ending when all players vote

### ISSUE THREAD

**Issue by 0xDrMoe** [0xDrMoe/TownofHost-Enhanced#312]
Original Poster: shapmaster
Original Report Date: 04/18/2023
Original Version: TOH Edited v2.2.9
Attempted Fix: No
Logs? [TOHE-v2.2.9-2023-04-18_20.08.48.log](https://github.com/0xDrMoe/TownofHost-Enhanced/files/13551313/TOHE-v2.2.9-2023-04-18_20.08.48.log)

Been a known issue since OG TOH - Possible fix? I have experienced this before.

**Comment by Tommy-XL** [comment]
Fixed (i think) #329

**Comment by Tommy-XL** [comment]
If it is not fixed, then it is a vanilla bug
