### ISSUE TITLE
Ask : Does colors change roles beheviour ?

### ISSUE THREAD

**Issue by Lorddistrict** [0xDrMoe/TownofHost-Enhanced#314]
Hi,

I would ask you if there is some problem with colors roles.
We updated colors to have only 4 colors :
- crewmates (light blue)
- neutrals (light gray)
- impostors (red)
- add-ons (yellow)
- seller (green)

But since, we've got few bugs : 
- Transporter : teleported me inside walls on Polus
- Enigma : infos was wrong (number guess & wrong roles)
- Sheriff : click on kill button -> Sheriff die
- Counterfeiter : kill impostors and let crew alive
- Jester : Has been voted but doesn't won the game

Thank you !

**Comment by ryuk201198** [comment]
1. All the transporting roles can cause the issue of players transporting into walls, it has been fixed.
2. I would need logs
3. I would need logs
4. I would need logs
5. Jester has a setting Number of meetings that has to be passed to win. If the number hasn't been satisfied jester won't win on ejection.

Do you have discord? If you do i'd highly appreciate it if you make bug reports on discord.
Discord link:- https://www.discord.gg/tohe

**Comment by Lorddistrict** [comment]
Colors doesn't impact your code did it ?
For others reports I'm going to use discord.

**Comment by ryuk201198** [comment]
> Colors doesn't impact your code did it ? For others reports I'm going to use discord.

Nope, colors have nothing to do with it. And thx for using the discord!!
