### ISSUE TITLE
Translation in French

### ISSUE THREAD

**Issue by Hoax017** [0xDrMoe/TownofHost-Enhanced#319]
How can I correct the French translation ?

**Comment by FuroYT** [comment]
We have social life’s so we can be late sometimes

**Comment by Hoax017** [comment]
if you need help i'm french

**Comment by FuroYT** [comment]
we are too

**Comment by Ultradragon005** [comment]
just ask the baguettes man

**Comment by FuroYT** [comment]
@Hoax017 then don’t use qwerty when typing in French lol we use azerty
