### ISSUE TITLE
Add MoreGamemodes proximity chat

### ISSUE THREAD

**Issue by PHGaming121** [0xDrMoe/TownofHost-Enhanced#343]
I was already talking about this in discords dev chat
Basically add the options for proximity chat from [MoreGamemodes](https://github.com/Rabek009/MoreGamemodes)

the chat looks like this: 
![Captura de Tela (248)](https://github.com/0xDrMoe/TownofHost-Enhanced/assets/76562427/d911f0b8-878e-4aba-a160-e81586da7b87)

Tasks:

 - [ Add Base of Proximity Chat ] 

- [ Fix errors(Like a spam of errors that happens when the match starts, making the mod completely glitch)  ] 

 - [ Fix a Bug that thew messages doesnt appear as expected (it appears normally on chat or it doesnt appear on name) ] 

- [ When adding it, fix a supposed bug with arrows (BloundHound and others) (thanks ryuk btw) ]

**Comment by PHGaming121** [comment]
idk how to do a task list lol

**Comment by NikoCat233** [comment]
What?

**Comment by PHGaming121** [comment]
> What?

u ever heard of more gamemodes mod?

**Comment by NikoCat233** [comment]
Yep

**Comment by PHGaming121** [comment]
COULD SOMEONE HELP US HERE??

**Comment by PHGaming121** [comment]
sorry for caps ;-;

**Comment by Pietrodjaowjao** [comment]
bro thats impossible, just close this issue, TOHE needs to change the player name every second, and the proximity chat uses the player name for the messages obviousily

**Comment by FuroYT** [comment]
and its restricted due to it editing the game's hud (which we cant do on vanilla)

**Comment by Ultradragon005** [comment]
hm. what if you try to return "Skill Issue" to the game if it dosen't work.

**Comment by PHGaming121** [comment]
> and its restricted due to it editing the game's hud (which we cant do on vanilla)

wait.. it doesnt edit the players name?

**Comment by PHGaming121** [comment]
im soooooooo confuseeed

**Comment by Gurge44** [comment]
> and its restricted due to it editing the game's hud (which we cant do on vanilla)

More Gamemodes is also host-only, you know that, right..?
They just change the player's name which is 100% doable and isn't even hard.

**Comment by Ultradragon005** [comment]
🤯🤯🤯🙀🙀🙀🗣💯💯💯

**Comment by PHGaming121** [comment]
also , @Gurge44 how did u added id support for /up / /setrole ?

**Comment by Gurge44** [comment]
You can just look at what I've done in TOHE+

**Comment by PHGaming121** [comment]
i already tried it, it always says "Invalid Arguments"

the format is /setrole ID ROLE, right?

**Comment by Gurge44** [comment]
yes

**Comment by PHGaming121** [comment]
Almost done, but closing

**Comment by PHGaming121** [comment]
REOPENING THIS BECAUSE BUGS

**Comment by PHGaming121** [comment]
- [ ] Fix Message Doesnt Disappear after some time (like 5/6 seconds)

- [ ] add Only Impostor And (Optional, but cool) Only Lovers chats

**Comment by PHGaming121** [comment]
> * [ ]  Fix Message Doesnt Disappear after some time (like 5/6 seconds)
> * [ ]  add Only Impostor And (Optional, but cool) Only Lovers chats

someone heeeeelp

**Comment by PHGaming121** [comment]
@Gurge44 HELP MEEEEEEEEEE

**Comment by Ultradragon005** [comment]
try this:
foreach (atom in universe)
{
 NotifyAllPlayers();
}

**Comment by PHGaming121** [comment]
> try this: foreach (atom in universe) { NotifyAllPlayers(); }

u serious? 💀

**Comment by Ultradragon005** [comment]
https://tenor.com/view/smile-laughing-laugh-gif-26377590

**Comment by PHGaming121** [comment]
> > try this: foreach (atom in universe) { NotifyAllPlayers(); }
> 
> u serious? 💀

i didnt even tried it lol
ik it isnt gonna work

**Comment by Ultradragon005** [comment]
> > * [ ]   Fix Message Doesnt Disappear after some time (like 5/6 seconds)
> > * [ ]   add Only Impostor And (Optional, but cool) Only Lovers chats
> 
> someone heeeeelp

lovers chat:
using S = System;
using C = System.Collections.Generic;

class P
{
    static void M()
    {
        int G = 6; int[,] A = R(G);
        S.CW("M:"); PM(A);

        var D = DFS(A, 0);
        S.CW("DFS:"); PT(D);

        var C = ACO(D);
        S.CW("Result ACO:"); PT(C);
    }

    static int[,] R(int S) { var R = new int[S, S]; var N = new S.Random(); for (int I = 0; I < S; I++) for (int J = I + 1; J < S; J++) R[I, J] = R[J, I] = N.Next(2); return R; }

    static void PM(int[,] M) { int S = M.GetLength(0); for (int I = 0; I < S; I++) { for (int J = 0; J < S; J++) S.CW($"{M[I, J]}\t"); S.CW(); } S.CW(); }

    static C.List<int> DFS(int[,] G, int N) { var T = new C.List<int>(); var S = new C.Stack<int>(); var V = new bool[G.GetLength(0)]; S.Push(N); while (S.Count > 0) { int C = S.Pop(); if (!V[C]) { V[C] = true; T.Add(C); for (int I = G.GetLength(0) - 1; I >= 0; I--) if (G[C, I] == 1 && !V[I]) S.Push(I); } } return T; }

    static C.List<int> ACO(C.List<int> T) { var R = new C.List<int>(); foreach (var N in T) R.Add(N * 2 + 1); return R; }

    static void PT(C.List<int> T) { foreach (var N in T) S.CW($"{N}\t"); S.CW(); S.CW(); }
}

**Comment by PHGaming121** [comment]
dear devs
i just... give up.
i just cant code, doesnt even know the basics of c#...
but, plz leave this issue open, so... if someone decides to do this, they can use this issue as an base for objectives
also, i apologize for the excessive asks for help on discord, its because its a cool feature for me, so i tried adding it, didnt have sucess btw. As i couldnt add it, i asked for devs help, but i asked... too much ._.

idk if i can learn a programming language like c#, but if someday i learn, i will **try** to add  ore features in tohe, maybe even new roles...

- PH Gaming

**Comment by Ultradragon005** [comment]
> dear devs i just... give up. i just cant code, doesnt even know the basics of c#... but, plz leave this issue open, so... if someone decides to do this, they can use this issue as an base for objectives also, i apologize for the excessive asks for help on discord, its because its a cool feature for me, so i tried adding it, didnt have sucess btw. As i couldnt add it, i asked for devs help, but i asked... too much ._.
> 
> idk if i can learn a programming language like c#, but if someday i learn, i will **try** to add ore features in tohe, maybe even new roles...
> 
> * PH Gaming

here's what u gonna do, wwatch this: https://www.youtube.com/watch?v=GhQdlIFylQ8&ab_channel=freeCodeCamp.org, learn this: https://www.w3schools.com/cs/index.php and do these https://www.w3resource.com/csharp-exercises/. Then mess with TOHE source code. and if neccessary ask for help then

**Comment by PHGaming121** [comment]
![Captura de Tela (305)](https://github.com/0xDrMoe/TownofHost-Enhanced/assets/76562427/4f30c959-c070-4e0e-941a-de85b2964b85)

wait, if this works, maybe it can work for the preivate chats?

**Comment by Ultradragon005** [comment]
> wait, if this works, maybe it can work for the private chats?

litteraly ignoring the glaringly obvious warning below it.....

**Comment by LucaDoyle** [comment]
open a new issue for a seperate issue
