### ISSUE TITLE
[Feature] Prioritize Doppelganger functionality over Jinx

### ISSUE THREAD

**Issue by aaronliu0130** [0xDrMoe/TownofHost-Enhanced#395]
i.e. make it so when the Doppelganger kills a Jinx, they get the Jinx's identity first before dying if Jinx have ability i.e. Doppelganger die has Jinx's body. create confusion as to if Jinx was shapeshifter

**Comment by Tommy-XL** [comment]
Please, make your suggestions for improving the role in the discord server:
https://discord.gg/tohe
