### ISSUE TITLE
Cannot host games

### ISSUE THREAD

**Issue by RawrMonster91** [0xDrMoe/TownofHost-Enhanced#725]
When I try to TOHE host a game, the screen remains black for a long time and then I get the message that my account cannot be authenticated.  

If it doesn't do that, then I am getting this notification
![image](https://github.com/0xDrMoe/TownofHost-Enhanced/assets/162005118/3f331c3e-a1ad-4711-90e2-2fc84fe2efff)

How do I correct this issue?

**Comment by Tommy-XL** [comment]
https://github.com/0xDrMoe/TownofHost-Enhanced?tab=readme-ov-file#legal-license-notice

**Comment by Tommy-XL** [comment]
Oh wait

**Comment by Tommy-XL** [comment]
What version do you have?

**Comment by RawrMonster91** [comment]
> What version do you have?

This one

![image](https://github.com/0xDrMoe/TownofHost-Enhanced/assets/162005118/c37d956a-d8de-4be7-9bc6-04ac514914ce)

**Comment by Tommy-XL** [comment]
Try change region
![image](https://github.com/0xDrMoe/TownofHost-Enhanced/assets/104814436/37002e63-4148-455d-aaa2-f6aec7e048ca)

**Comment by RawrMonster91** [comment]
Yup! That was the issue! Thank you so much!
