### ISSUE TITLE
Role Assignment Algorithms

### ISSUE THREAD

**Issue by RawrMonster91** [0xDrMoe/TownofHost-Enhanced#727]
Would you possibly be able to help me with how the different role assignment algorithms work? I cannot seem to be able to find the information on it. Below I've listed the different ones available.

Default, .net system.random, hash random, xorshift, mersenne twister

**Comment by Ultradragon005** [comment]
![image](https://github.com/0xDrMoe/TownofHost-Enhanced/assets/143632280/ac02013f-662a-4818-987b-41c6ec0a7b4c)
![image](https://github.com/0xDrMoe/TownofHost-Enhanced/assets/143632280/9e9606ca-d4b8-4fbf-b235-d1e49f36470a)
![image](https://github.com/0xDrMoe/TownofHost-Enhanced/assets/143632280/6061f214-8162-4f32-b41d-6d00ebaafefe)
![image](https://github.com/0xDrMoe/TownofHost-Enhanced/assets/143632280/26887f9c-300e-46e2-8b34-8643de3ad784)
Google if you want detailed info on how they work

**Comment by RawrMonster91** [comment]
Thank you!

**Comment by RawrMonster91** [comment]
I was mainly asking because I had enough roles for every crew mate to have one but some people were still left with out a role. Is there a way to make sure everyone gets a role?

**Comment by MargaretTheFool** [comment]
if you have neutral roles on make sure you have the minimums and maximums set
its also a lot easier to get help if you ask in the discord

**Comment by RawrMonster91** [comment]
Will do. Thank you!
